USE Stocks;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Tickers')
	BEGIN
		DROP TABLE Tickers;
	END

CREATE TABLE Tickers (
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	Ticker NVARCHAR(50) NOT NULL
);
