USE Stocks;
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'IncomeStatements')
	BEGIN
		DROP TABLE IncomeStatements;
	END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TimeSeriesDaily')
	BEGIN
		DROP TABLE TimeSeriesDaily;
	END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Tickers')
	BEGIN
		DROP TABLE Tickers;
	END

CREATE TABLE Tickers (
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	Ticker NVARCHAR(50) NOT NULL,
	IsInPortfolio BIT NOT NULL DEFAULT 0 
);

CREATE UNIQUE INDEX Ticker_Index ON [dbo].[Tickers] (Ticker);

CREATE TABLE TimeSeriesDaily (
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	[Date] DATETIME NOT NULL,
	[Close] NVARCHAR(250) NOT NULL,
	[High] NVARCHAR(250) NOT NULL,
	[Low] NVARCHAR(250) NOT NULL,
	[Open] NVARCHAR(250) NOT NULL,
	[Volumne] NVARCHAR(1000) NOT NULL,
	Ticker UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tickers(ID)
);

CREATE UNIQUE INDEX Date_Index ON [dbo].[TimeSeriesDaily] (Date, Ticker)

CREATE TABLE IncomeStatements (
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	FiscalDateEnding DATETIME NOT NULL,
	ReportedCurrency NVARCHAR(100) NOT NULL,
	GrossProfit NVARCHAR(MAX) NOT NULL,
	TotalRevenue NVARCHAR(MAX) NOT NULL,
	CostOfRevenue NVARCHAR(MAX) NOT NULL,
	CostofGoodsAndServicesSold NVARCHAR(MAX) NOT NULL,
	OperatingIncome NVARCHAR(MAX) NOT NULL,
	SellingGeneralAndAdministrative NVARCHAR(MAX) NOT NULL,
	ResearchAndDevelopment NVARCHAR(MAX) NOT NULL,
	OperatingExpenses NVARCHAR(MAX) NOT NULL,
	InvestmentIncomeNet NVARCHAR(MAX) NOT NULL,
	NetInterestIncome NVARCHAR(MAX) NOT NULL,
	InterestIncome NVARCHAR(MAX) NOT NULL,
	InterestExpense NVARCHAR(MAX) NOT NULL,
	NonInterestIncome NVARCHAR(MAX) NOT NULL,
	OtherNonOperatingIncome NVARCHAR(MAX) NOT NULL,
	Depreciation NVARCHAR(MAX) NOT NULL,
	DepreciationAndAmortization NVARCHAR(MAX) NOT NULL,
	IncomeBeforeTax NVARCHAR(MAX) NOT NULL,
	IncomeTaxExpense NVARCHAR(MAX) NOT NULL,
	InterestAndDebtExpense NVARCHAR(MAX) NOT NULL,
	NetIncomeFromContinuingOperations NVARCHAR(MAX) NOT NULL,
	ComprehensiveIncomeNetOfTax NVARCHAR(MAX) NOT NULL,
	Ebit NVARCHAR(MAX) NOT NULL,
	Ebitda NVARCHAR(MAX) NOT NULL,
	NetIncome NVARCHAR(MAX) NOT NULL,
	Ticker UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tickers(ID)
);

CREATE UNIQUE INDEX Date_Index ON [dbo].[IncomeStatements] (FiscalDateEnding, Ticker)